spring:
  datasource:
    url: jdbc:h2:file:./SmartStartupDatabase
#    todo move to env
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  h2:
    console.path: /h2-console
    console.settings.trace: true
    console.settings.web-allow-others: true
    console.enabled: true