spring:
  datasource:
    url: jdbc:h2:file:./SmartStartupDatabase
#    todo move to env
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: false
